application: postdatabase
version: 0-3-4-beta
runtime: python
api_version: 1

handlers:
- url: /static/html
  static_dir: static/html
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /static/images
  static_dir: static/images
- url: /settings.*
  script: settings.py
  login: required
- url: /admin.*
  script: admin.py
  login: admin
- url: /wall/.*
  script: wall.py
- url: /post/.*
  script: post.py
- url: /tools/.*
  script: tools.py
- url: /.*
  script: main.py
