from google.appengine.ext import db

class Wall(db.Model):
    owner = db.UserProperty(required=True)
    name = db.StringProperty(required=True,multiline=False)
    date = db.DateTimeProperty(auto_now_add=True)
    pageSize = db.IntegerProperty(required=True)
    allowEntry = db.BooleanProperty(required=True)
    allowRead = db.BooleanProperty(required=True)
    allowHtml = db.BooleanProperty(required=True)
    wallStyle = db.IntegerProperty(required=True)
    nickLabel = db.StringProperty(multiline=False,required=False)
    nick2Label = db.StringProperty(multiline=False,required=False)
    postAreaLabel = db.StringProperty(multiline=False,required=False)
    postButtonLabel = db.StringProperty(multiline=False,required=False)
    resetButtonLabel = db.StringProperty(multiline=False,required=False)
    lastSavedFirst = db.BooleanProperty(required=True)
    postStyle = db.IntegerProperty(required=True)
    dateStyle = db.IntegerProperty(required=True)
    formWidth = db.IntegerProperty(required=True)
    formHeight = db.IntegerProperty(required=True)
    infoBackgroundColor = db.StringProperty(multiline=False,required=True)
    infoForegroundColor = db.StringProperty(multiline=False,required=True)
    emailOnSubmit=db.BooleanProperty(required=True)
    
class Post(db.Model):
    wall = db.ReferenceProperty(Wall,required=True)
    nick =  db.StringProperty(multiline=False,required=False)
    nick2 = db.StringProperty(multiline=False,required=False)
    value = db.TextProperty(required=True)
    date = db.DateTimeProperty(auto_now_add=True)
    order = db.DateTimeProperty(auto_now_add=True)
